### PR TITLE
tightening up nav node spacing in content view

### PR DESCRIPTION
**Pull request by d88naimi**
tighten up the node height to be more consistent for code and schema view 
Original ticket: https://github.com/zesty-io/manager-ui/issues/278

### CODE REVIEW

**Comment by d88naimi** [comment]
@stuart Original ticket:https://github.com/zesty-io/manager-ui/issues/278

Ive updated the line height in parent.less to match zeplins line height instructions https://app.zeplin.io/project/5bb69f5bdfef6551f65f76e8/screen/5bc075fcc5be3f1906407c79

This now makes all nav height nodes consistent for Content, Node, and Schema view

**Comment by shrunyan** [comment]
@d88naimi would you provide a screenshot of multi-line nav link text. Want to ensure we have good visual in that situation.

**Comment by d88naimi** [comment]
@shrunyan 


CONTENT VIEW
Screen Shot 2020-10-22 at 12 11 29 PM

SCHEMA VIEW
Screen Shot 2020-10-22 at 12 12 01 PM


CODE VIEW
Screen Shot 2020-10-22 at 12 12 24 PM

**Comment by shrunyan** [comment]
@d88naimi none of the links in this nav are multi-line

**Comment by d88naimi** [comment]
@shrunyan 
Screen Shot 2020-10-23 at 9 36 09 AM

**Comment by d88naimi** [comment]
@shrunyan Multiline items are now aligned nicely with icons. 

Screen Shot 2020-10-23 at 10 25 10 AM

**Pull request merged**
